App\Entity\Categoria:
  attributes:
    normalization_context:
      groups: [category_read]
  collectionOperations:
    register:
      method: POST      
      path: /categoria/registerCategoria
      controller: App\Api\Action\Categoria\RegisterCategoria
      normalization_context:
        groups: [category_read]
      denormalization_context:
        groups: [category_create]
      openapi_context:
        summary: Creación de categoria
    registerSubCategoria:
      method: POST      
      path: /categoria/registerSubCategoria
      controller: App\Api\Action\Categoria\RegisterSubCategoria
      normalization_context:
        groups: [sub_category_read]      
      denormalization_context:
        groups: [sub_category_create]
      openapi_context:
        summary: Creación de sub categoria        
    cargarCategorias:
      method: POST      
      path: /categoria/cargarCategorias
      controller: App\Api\Action\Categoria\CargarCategorias
      deserialize: false
      openapi_context:
        summary: Carga automática de categorias y sub categorias
    clasificadosCategoria:
      method: POST      
      path: /categoria/clasificadosCategoria
      controller: App\Api\Action\Categoria\CladificadosPorCategoria
      deserialize: false
      openapi_context:
        summary: Mostrar los clasificados por categoria        
    paginarCategorias:
      method: POST      
      path: /categoria/paginarCategorias
      controller: App\Api\Action\Categoria\PaginarCategorias
      deserialize: false
      openapi_context:
        summary: Mostrar los clasificados por categoria                
    paginarSubCategorias:
      method: POST      
      path: /categoria/paginarSubCategorias
      controller: App\Api\Action\Categoria\PaginarSubCategorias
      deserialize: false
      openapi_context:
        summary: Mostrar los clasificados por categoria                        