App\Entity\Categoria:
  attributes:
    normalization_context:
      groups: [category_read]
  collectionOperations:
    register:
      method: POST      
      path: /categoria/registerCategoria
      controller: App\Api\Action\Categoria\RegisterCategoria
      normalization_context:
        groups: [category_read]
      denormalization_context:
        groups: [category_create]
      openapi_context:
        summary: Creación de categoria
    registerSubCategoria:
      method: POST      
      path: /categoria/registerSubCategoria
      controller: App\Api\Action\Categoria\RegisterSubCategoria
      normalization_context:
        groups: [sub_category_read]      
      denormalization_context:
        groups: [sub_category_create]
      openapi_context:
        summary: Creación de sub categoria        
    cargarCategorias:
      method: POST      
      path: /categoria/cargarCategorias
      controller: App\Api\Action\Categoria\CargarCategorias
      deserialize: false
      openapi_context:
        summary: Carga automática de categorias y sub categorias      
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  inicio:
                    type: string                          
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    resultado:
                      type: bolean         
                    mensaje:
                      type: string     
    clasificadosCategoria:
      method: POST      
      path: /categoria/clasificadosCategoria
      controller: App\Api\Action\Categoria\CladificadosPorCategoria
      deserialize: false
      openapi_context:
        summary: Clasificados por categoria        
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  idCategoria:
                    type: string
                    required: true                                      
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string 

    paginarCategorias:
      method: POST      
      path: /categoria/paginarCategorias
      controller: App\Api\Action\Categoria\PaginarCategorias
      deserialize: false
      openapi_context:
      openapi_context:
        summary: Paginar categorias                              
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  tam:
                    type: string
                    required: true                    
                  pagina:
                    type: string
                    required: true                                        
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: array 
    paginarSubCategorias:
      method: POST      
      path: /categoria/paginarSubCategorias
      controller: App\Api\Action\Categoria\PaginarSubCategorias
      deserialize: false
      openapi_context:
        summary: Paginar sub categorias                              
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  idPadre:
                    type: string
                    required: true
                  tam:
                    type: string
                    required: true                    
                  pagina:
                    type: string
                    required: true                                        
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: array                              