App\Entity\Categoria:
  attributes:
    normalization_context:
      groups: [category_read]
  collectionOperations:
    register:
      method: POST      
      path: /categoria/registerCategoria
      controller: App\Api\Action\Categoria\RegisterCategoria
      normalization_context:
        groups: [category_read]
      denormalization_context:
        groups: [category_create]
      openapi_context:
        summary: Creación de categoria
    registerSubCategoria:
      method: POST      
      path: /categoria/registerSubCategoria
      controller: App\Api\Action\Categoria\RegisterSubCategoria
      normalization_context:
        groups: [sub_category_read]      
      denormalization_context:
        groups: [sub_category_create]
      openapi_context:
        summary: Creación de sub categoria        
    cargarCategorias:
      method: POST      
      path: /categoria/cargarCategorias
      controller: App\Api\Action\Categoria\CargarCategorias
      deserialize: false
      openapi_context:
        summary: Carga automática de categorias y sub categorias