App\Entity\Categoria:
  attributes:
    id:
      groups: [category_read,sub_category_read]
    name:
      groups: [category_read,sub_category_read, category_create,sub_category_create, category_update]
    path:
      groups: [category_read,sub_category_read, category_create,sub_category_create, category_update]    
    padre:
      groups: [sub_category_read]    
    idPadre:  
      groups: [sub_category_create]        
    createdAt:
      groups: [category_read,sub_category_read]
    updatedAt:
      groups: [category_read,sub_category_read]
